/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "fff.h"
#include "linkedListBuffer_t.h"
#include <stdio.h>
#include <assert.h>
#include <time.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_rejectWhenFull(void);
extern void test_pushAndPop(void);
extern void test_pushAndPopReversed(void);
extern void test_removeEntriesAndInsertIntoNonEmpty(void);
extern void test_removeEntriesAndInsertIntoNonEmptyReversed(void);
extern void test_allocBefore(void);
extern void test_allocAfter(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test_linkedList.c");
  run_test(test_rejectWhenFull, "test_rejectWhenFull", 45);
  run_test(test_pushAndPop, "test_pushAndPop", 82);
  run_test(test_pushAndPopReversed, "test_pushAndPopReversed", 140);
  run_test(test_removeEntriesAndInsertIntoNonEmpty, "test_removeEntriesAndInsertIntoNonEmpty", 202);
  run_test(test_removeEntriesAndInsertIntoNonEmptyReversed, "test_removeEntriesAndInsertIntoNonEmptyReversed", 316);
  run_test(test_allocBefore, "test_allocBefore", 433);
  run_test(test_allocAfter, "test_allocAfter", 474);

  return UnityEnd();
}
